"""
JLC Joy Caption (Lite) — ComfyUI Node Wrapper

Compact direct-IMAGE / Run Plan captioning frontend for JoyCaption/LLaVA models.

Standalone mode:
- accepts direct ComfyUI IMAGE input
- returns caption text only in a small, friendly UI

CaptionForge Run Plan mode:
- accepts direct IMAGE input and/or the Run Plan input_path
- expands the Run Plan into per-caption-instance settings
- writes TXT audit sidecars into the shared output_dir
- appends CaptionForge Pass A records to the shared captions.jsonl
- returns all generated captions sequentially in the caption output
- returns the JSONL records generated by this node execution

The reusable model logic lives in jlc_joy_caption_engine.py.
"""

from __future__ import annotations

MANIFEST = {
    "name": "JLC Joy Caption (Lite)",
    "version": (1, 1, 0),
    "author": "J. L. Córdova",
    "description": (
        "Compact ComfyUI frontend for JoyCaption/LLaVA-family captioning. In "
        "standalone mode it behaves as a small direct-IMAGE caption node. When a "
        "CaptionForge Run Plan is connected, it becomes a production Pass A evidence "
        "node: it uses shared input_path/output_dir routing, per-run seeds and "
        "sampling schedules, writes TXT audit sidecars, appends common JSONL evidence "
        "records, and still returns readable captions in the UI."
    ),
}

import json
from datetime import datetime
from pathlib import Path
import time

import numpy as np
import torch
from PIL import Image

import folder_paths

from .jlc_joy_caption_engine import (
    CaptionRecord,
    CleanupConfig,
    GenerationConfig,
    JoyCaptionConfig,
    JoyCaptionEngine,
    MEMORY_EFFICIENT_CONFIGS,
    MODEL_REGISTRY,
    append_jsonl_records,
    record_to_json,
    timestamp,
    write_run_config_json,
    write_text_sidecar,
)
from .engines.run_plan.captionforge_run_plan import expand_captionforge_runs


JLC_JOY_MODEL_ROOT = Path(folder_paths.models_dir) / "LLM" / "JLC_JoyCaption"
DEFAULT_JSONL_FILENAME = "captions.jsonl"
_SUPPORTED_IMAGE_SUFFIXES = {".png", ".jpg", ".jpeg", ".webp", ".bmp", ".tif", ".tiff"}

DEFAULT_LITE_PROMPT = (
    "You are an image captioning assistant. Describe the image in a highly "
    "detailed, literal, and visually grounded way. Focus only on visible details. "
    "Include subject appearance, clothing, pose, body position, hands, facial "
    "expression, hairstyle, accessories, lighting, background, textures, colors, "
    "and spatial relationships. Avoid speculation, avoid backstory, avoid "
    "opinions, and avoid mentioning things not clearly visible."
)

LITE_SYSTEM_PROMPT = (
    "You are a helpful image-captioning assistant. Describe only what is visible "
    "in the image. Do not invent unseen context."
)


def _tensor_to_pil(image_tensor) -> list[Image.Image]:
    """Convert ComfyUI IMAGE tensor [B,H,W,C] float 0..1 into PIL RGB images."""
    if image_tensor is None:
        return []

    if isinstance(image_tensor, torch.Tensor):
        image_tensor = image_tensor.detach().cpu()

    if image_tensor.ndim == 3:
        image_tensor = image_tensor.unsqueeze(0)

    images: list[Image.Image] = []
    for img in image_tensor:
        arr = img.numpy()
        arr = np.clip(arr * 255.0, 0, 255).astype(np.uint8)
        images.append(Image.fromarray(arr).convert("RGB"))

    return images


def _safe_source_name(value: str) -> str:
    cleaned = []
    for ch in value.replace("\\", "/"):
        if ch.isalnum() or ch in {"-", "_", "."}:
            cleaned.append(ch)
        elif ch == "/":
            cleaned.append("__")
        else:
            cleaned.append("_")
    out = "".join(cleaned).strip("._")
    return out or "image"


def _iter_input_path_images(input_path: str, recursive: bool, filename_glob: str) -> list[tuple[str, Path]]:
    root = Path(str(input_path or "").strip())
    if not root:
        return []
    if not root.exists():
        raise RuntimeError(f"CaptionForge input_path does not exist: {root}")

    glob_text = (filename_glob or "*").strip() or "*"

    if root.is_file():
        if root.suffix.lower() not in _SUPPORTED_IMAGE_SUFFIXES:
            raise RuntimeError(f"CaptionForge input_path is not a supported image file: {root}")
        return [(_safe_source_name(root.stem), root)]

    pattern_iter = root.rglob(glob_text) if recursive else root.glob(glob_text)
    paths = sorted(
        p for p in pattern_iter
        if p.is_file() and p.suffix.lower() in _SUPPORTED_IMAGE_SUFFIXES
    )

    items: list[tuple[str, Path]] = []
    for path in paths:
        rel = path.relative_to(root).with_suffix("")
        items.append((_safe_source_name(str(rel)), path))
    return items


def _open_image(path: Path) -> Image.Image:
    with Image.open(path) as im:
        return im.convert("RGB")


def _make_jsonl_string(records: list[CaptionRecord]) -> str:
    return "\n".join(json.dumps(record_to_json(r), ensure_ascii=False) for r in records)


def _run_txt_path(output_dir: Path, source_name: str, run_count: int, run_index: int) -> Path:
    if run_count <= 1:
        return output_dir / f"{source_name}.txt"
    return output_dir / f"{source_name}__cf_run_{run_index:02d}.txt"


class JLC_JoyCaptionLite:
    """Minimal JoyCaption node; Run Plan turns it into a CaptionForge evidence node."""

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "model": (
                    list(MODEL_REGISTRY.keys()),
                    {
                        "default": "llama-joycaption-beta-one-hf-llava",
                        "tooltip": (
                            "Select the JoyCaption/LLaVA-family model. Models are loaded from "
                            "ComfyUI/models/LLM/JLC_JoyCaption/."
                        ),
                    },
                ),
                "memory_mode": (
                    list(MEMORY_EFFICIENT_CONFIGS.keys()),
                    {
                        "default": (
                            "Balanced (8-bit)"
                            if "Balanced (8-bit)" in MEMORY_EFFICIENT_CONFIGS
                            else list(MEMORY_EFFICIENT_CONFIGS.keys())[0]
                        ),
                        "tooltip": (
                            "Joy model memory mode. Balanced (8-bit) uses bitsandbytes load-time "
                            "quantization and is the recommended CaptionForge default for 16 GB "
                            "VRAM systems."
                        ),
                    },
                ),
                "keep_loaded": (
                    "BOOLEAN",
                    {
                        "default": True,
                        "tooltip": (
                            "Keep the model cached after captioning for faster repeated runs. "
                            "CaptionForge cache policy may still evict it when another caption "
                            "model must load."
                        ),
                    },
                ),
                "system_prompt": (
                    "STRING",
                    {
                        "default": DEFAULT_LITE_PROMPT,
                        "multiline": True,
                        "tooltip": (
                            "Lite caption instruction. This is passed as the Joy caption prompt "
                            "while a conservative internal system message is used. Run Plan controls "
                            "routing, seed/sampling schedules, size, token budget, and evidence "
                            "output; this prompt remains the Lite node's model-specific caption style."
                        ),
                    },
                ),
                "max_new_tokens": (
                    "INT",
                    {
                        "default": 384,
                        "min": 16,
                        "max": 4096,
                        "step": 8,
                        "tooltip": (
                            "Standalone token budget. When a CaptionForge Run Plan is connected, "
                            "this is overridden by the Run Plan's shared max_new_tokens."
                        ),
                    },
                ),
                "temperature": (
                    "FLOAT",
                    {
                        "default": 0.75,
                        "min": 0.0,
                        "max": 2.0,
                        "step": 0.01,
                        "tooltip": (
                            "Standalone sampling temperature. When a CaptionForge Run Plan is "
                            "connected, this is overridden by the Run Plan temperature schedule."
                        ),
                    },
                ),
                "top_p": (
                    "FLOAT",
                    {
                        "default": 0.90,
                        "min": 0.0,
                        "max": 1.0,
                        "step": 0.01,
                        "tooltip": (
                            "Standalone top-p sampling value. When a CaptionForge Run Plan is "
                            "connected, this is overridden by the Run Plan top-p schedule."
                        ),
                    },
                ),
                "top_k": (
                    "INT",
                    {
                        "default": 50,
                        "min": 0,
                        "max": 500,
                        "step": 1,
                        "tooltip": (
                            "Standalone top-k sampling limit. When a CaptionForge Run Plan is "
                            "connected, this is overridden by the Run Plan top-k schedule."
                        ),
                    },
                ),
            },
            "optional": {
                "image": (
                    "IMAGE",
                    {
                        "tooltip": (
                            "Image or batch of images to caption. When a CaptionForge Run Plan "
                            "also supplies input_path, both sources are captioned."
                        ),
                    },
                ),
                "captionforge_run_config": (
                    "CAPTIONFORGE_RUN_CONFIG",
                    {
                        "tooltip": (
                            "Optional shared CaptionForge Run Plan. When connected, this Lite node "
                            "switches into Pass A evidence mode: shared input_path/output_dir, "
                            "per-run seeds and schedules, TXT audit sidecars, common captions.jsonl, "
                            "and run config export."
                        ),
                    },
                ),
            },
        }

    RETURN_TYPES = ("STRING", "STRING", "STRING")
    RETURN_NAMES = ("caption", "jsonl_records", "resolved_prompt")
    FUNCTION = "caption"
    CATEGORY = "JLC/Captioning"

    @classmethod
    def IS_CHANGED(cls, **kwargs):
        return float("NaN")

    def caption(
        self,
        model,
        memory_mode,
        keep_loaded,
        system_prompt,
        max_new_tokens,
        temperature,
        top_p,
        top_k,
        image=None,
        captionforge_run_config=None,
    ):
        run_plan_connected = bool(captionforge_run_config)
        prompt = (system_prompt or DEFAULT_LITE_PROMPT).strip() or DEFAULT_LITE_PROMPT

        run_plan = expand_captionforge_runs(
            captionforge_run_config,
            widget_captions_per_image=1,
            widget_seed=-1,
            widget_temperature=float(temperature),
            widget_top_p=float(top_p),
            widget_top_k=int(top_k),
            widget_max_new_tokens=int(max_new_tokens),
            widget_max_size=1024,
            widget_trigger_word="",
            widget_output_dir="",
            widget_input_path="",
            widget_recursive=True,
            widget_filename_glob="*",
        )
        first_run = run_plan[0]

        generation = GenerationConfig(
            max_new_tokens=int(first_run.max_new_tokens),
            temperature=float(first_run.temperature),
            top_p=float(first_run.top_p),
            top_k=int(first_run.top_k),
            repetition_penalty=1.0,
            seed=first_run.seed,
        )

        cleanup = CleanupConfig(
            trigger="",
            prefix=(f"{first_run.trigger_word}," if first_run.trigger_word else ""),
            suffix="",
            forbidden_phrases=[],
            replacement_rules=[],
        )

        joy_config = JoyCaptionConfig(
            model_name=model,
            model_path="",
            model_root=str(JLC_JOY_MODEL_ROOT),
            memory_mode=memory_mode,
            dtype="bf16",
            device="auto",
            trust_remote_code=True,
            keep_loaded=bool(keep_loaded),
            quiet_transformers_load=True,
            max_size=int(first_run.max_size),
            system_prompt=LITE_SYSTEM_PROMPT,
            prompt=prompt,
            allow_download=True,
            use_comfy_model_management=True,
        )

        engine = JoyCaptionEngine(config=joy_config, generation=generation, cleanup=cleanup)

        direct_images = [(f"comfy_image_{i:04d}", pil) for i, pil in enumerate(_tensor_to_pil(image))]
        file_images: list[tuple[str, Path]] = []
        if first_run.input_path:
            file_images = _iter_input_path_images(first_run.input_path, first_run.recursive, first_run.filename_glob)

        if direct_images and file_images:
            print(
                "[CaptionForge] IMAGE input and Run Plan input_path are both active; "
                "captioning both sources."
            )

        if not direct_images and not file_images:
            raise RuntimeError(
                "No image input found. Connect an IMAGE input or provide input_path in the "
                "CaptionForge Run Plan."
            )

        output_dir = Path(first_run.output_dir) if first_run.output_dir else Path(folder_paths.get_output_directory()) / "jlc_joy_caption_lite"
        if run_plan_connected:
            output_dir.mkdir(parents=True, exist_ok=True)

        jsonl_path = output_dir / DEFAULT_JSONL_FILENAME
        all_records: list[CaptionRecord] = []
        records_to_jsonl: list[CaptionRecord] = []

        engine.load()

        if run_plan_connected:
            write_run_config_json(
                output_dir / f"jlc_joy_caption_lite_run_config_{timestamp()}.json",
                engine.build_run_config(),
                dry_run=False,
            )

        def process_one(source_name: str, pil: Image.Image):
            for run in run_plan:
                engine.generation = GenerationConfig(
                    max_new_tokens=int(run.max_new_tokens),
                    temperature=float(run.temperature),
                    top_p=float(run.top_p),
                    top_k=int(run.top_k),
                    repetition_penalty=1.0,
                    seed=run.seed,
                )
                engine.cleanup = CleanupConfig(
                    trigger="",
                    prefix=(f"{run.trigger_word}," if run.trigger_word else ""),
                    suffix="",
                    forbidden_phrases=[],
                    replacement_rules=[],
                )
                engine.config.max_size = int(run.max_size)

                t0 = time.perf_counter()
                final_caption, raw_caption = engine.caption_pil(pil)
                dt = time.perf_counter() - t0
                print(f"[JLC Joy Caption Lite] Generation time run {run.ensemble_run_index}: {dt:.2f}s")

                record = CaptionRecord(
                    image=source_name,
                    caption=final_caption,
                    raw_caption=raw_caption,
                    model_name=model,
                    model_path=str(engine.local_model_path or ""),
                    prompt=prompt,
                    system_prompt=LITE_SYSTEM_PROMPT,
                    seed=run.seed,
                    temperature=run.temperature,
                    top_p=run.top_p,
                    top_k=run.top_k,
                    max_new_tokens=run.max_new_tokens,
                    max_size=int(run.max_size),
                    timestamp=datetime.now().isoformat(timespec="seconds"),
                    captionforge_pass="A",
                    model_family="joy",
                    ensemble_run_index=run.ensemble_run_index,
                    image_key=source_name,
                )
                all_records.append(record)
                
                if run_plan_connected:
                    records_to_jsonl.append(record)
                    append_jsonl_records(jsonl_path, [record], dry_run=False)
                    write_text_sidecar(
                        _run_txt_path(output_dir, source_name, len(run_plan), run.ensemble_run_index),
                        record.caption,
                        overwrite=True,
                        backup_existing=False,
                        dry_run=False,
                    )
                print(
                    f"[JLC Joy Caption Lite] Captioned {source_name} "
                    f"run {run.ensemble_run_index + 1}/{len(run_plan)}"
                )

        for source_name, pil in direct_images:
            process_one(source_name, pil)

        for source_name, path in file_images:
            process_one(source_name, _open_image(path))

        if not keep_loaded:
            engine.unload()

        caption_string = "\n\n".join(r.caption for r in all_records if r.status == "ok")
        jsonl_string = _make_jsonl_string(all_records)
        return (caption_string, jsonl_string, prompt)


NODE_CLASS_MAPPINGS = {
    "JLC_JoyCaptionLite": JLC_JoyCaptionLite,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "JLC_JoyCaptionLite": "\u2003JLC Joy Caption (Lite)",
}
